items = []
poll_interval_ms = 100
max_commits = 0
page_size = 10
sort_by = "custom"
sort_reverse = false
pinned = []
theme = "default"
git_app = "gitui"
compatibility_mode = false

[visits]

[fzf]
max_depth = 6
excludes = []
start_dir = "/Users/tareqmy/"
git_only = true
enabled = true
