[global]
toggle_status_bar = ["."]
help = ["?"]
close = [
    "esc",
    "q",
]

[home]
move_down = [
    "j",
    "down",
]
move_up = [
    "k",
    "up",
]
page_down = ["pagedown"]
page_up = ["pageup"]
home = ["home"]
end = ["end"]
add_repo = ["a"]
bulk_add = ["A"]
edit_repo = ["e"]
delete_repo = ["D"]
open_debug_logs = ["d"]
edit_labels = ["l"]
about = [
    "v",
    "V",
]
refresh = ["R"]
cycle_sort = ["o"]
toggle_sort_reverse = ["O"]
toggle_pin = ["p"]
open_settings = ["s"]
import_repo = ["i"]
open_git_app = ["g"]
search_repo = ["f"]
open_detail = [
    "enter",
    "right",
]

[navigation]
close_detail = [
    "esc",
    "q",
    "Q",
]
detail_help = ["?"]
cycle_focus_forward = ["w"]
cycle_focus_backward = ["W"]
refresh_detail = ["R"]
cycle_tab_forward = ["tab"]
cycle_tab_backward = ["backtab"]
go_to_tab_1 = ["1"]
go_to_tab_2 = ["2"]
go_to_tab_3 = ["3"]
go_to_tab_4 = ["4"]
go_to_tab_5 = ["5"]
go_to_tab_6 = ["6"]
go_to_tab_7 = ["7"]
go_to_tab_8 = ["8"]
